Repository aelamel/Pegasus-DS, pull requests merged in 2022-10, with the labels that each got.

#2 Technical setup
  .gitignore
  apps/front-app/.gitignore
  apps/front-app/index.html
  apps/front-app/package.json
  apps/front-app/public/vite.svg
  apps/front-app/src/App.css
  apps/front-app/src/App.jsx
  apps/front-app/src/assets/react.svg
  apps/front-app/src/index.css
  apps/front-app/src/main.jsx
  apps/front-app/vite.config.js
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: good first issue, hacktoberfest

#4 Adding ui-components library
  apps/front-app/package.json
  apps/front-app/src/App.jsx
  packages/ui-components/package.json
  packages/ui-components/src/components/Button/Button.tsx
  packages/ui-components/src/components/Button/index.ts
  packages/ui-components/src/components/index.ts
  packages/ui-components/src/index.ts
  packages/ui-components/tsconfig.json
  pnpm-lock.yaml
Labels: hacktoberfest, hacktoberfest-accepted

#8 Integrate storybook
  apps/front-app/src/App.jsx
  packages/ui-components/.npmrc
  packages/ui-components/.storybook/main.js
  packages/ui-components/.storybook/preview.js
  packages/ui-components/package-lock.json
  packages/ui-components/package.json
  packages/ui-components/src/components/Button/Button.stories.tsx
  packages/ui-components/src/components/Button/Button.tsx
  pnpm-lock.yaml
Labels: hacktoberfest

#10 add custom variant for mui button + custom theme
  package.json
  packages/ui-components/.storybook/preview.jsx
  packages/ui-components/src/components/Button/Button.stories.tsx
  packages/ui-components/src/components/Button/Button.tsx
  packages/ui-components/src/components/Button/styles.ts
  packages/ui-components/src/utils/theme.ts
  pnpm-lock.yaml
Labels: hacktoberfest

#14 adding input component (based on the desgin system on the figma templ…
  packages/ui-components/src/components/Input/Input.stories.tsx
  packages/ui-components/src/components/Input/Input.tsx
  packages/ui-components/src/components/Input/styles.ts
  packages/ui-components/src/utils/theme.ts
Labels: hacktoberfest

#16 adding typography component (based on the design system on the figma …
  packages/ui-components/src/components/Typography/Typography.stories.tsx
  packages/ui-components/src/components/Typography/Typography.tsx
  packages/ui-components/src/components/Typography/styles.ts
  packages/ui-components/src/utils/theme.ts
Labels: hacktoberfest
